# Generated by Django 2.2.12 on 2020-06-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200621_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
